[WIP] add simple/advanced wizard to datalayer
Terralego/terra-admin pull request #300
Opened 2020-10-07 12:33 UTC by CFarcy

2020-10-08 07:45 UTC, mabhub commented on src/modules/RA/DataLayer/components/tabs/MinisheetTab.js
> +      {minisheetEnable && advacedMinisheet && (
```suggestion
      {(minisheetEnable && advacedMinisheet) && (
```

2020-10-08 07:45 UTC, mabhub commented on src/modules/RA/DataLayer/components/tabs/MinisheetTab.js
> +      {minisheetEnable && !advacedMinisheet && (
```suggestion
      {(minisheetEnable && !advacedMinisheet) && (
```

2020-10-08 07:45 UTC, mabhub commented on src/modules/RA/DataLayer/components/tabs/PopupTab.js
> +      {popupEnable && !advancedPopup && (
```suggestion
      {(popupEnable && !advancedPopup) && (
```

2020-10-08 08:54 UTC, jrmi requested changes

2020-10-08 08:54 UTC, jrmi commented on src/modules/RA/DataLayer/components/tabs/MinisheetTab.js
> +  const { input: { value: advacedMinisheet } } = useField('settings.advanced_minisheet');
```suggestion
  const { input: { value: advancedMinisheet } } = useField('settings.advanced_minisheet');
```

2020-10-08 08:54 UTC, jrmi commented on src/modules/RA/DataLayer/components/tabs/PopupTab.js
> +        (advancedPopup && (
```suggestion
      {(popupEnable && advancedPopup) && (
```

2020-10-08 12:02 UTC, jrmi approved these changes

2020-10-14 07:36 UTC, jrmi approved these changes

2020-10-14 07:57 UTC, merged