WIP : CategorizeIcon
Terralego/terra-admin pull request #532
Opened 2023-04-28 22:35 UTC by Bo-Duke

Not done, some issues I don't get with react-final-form, changing one icon for a given category change all the others and some other weird stuff

2023-07-07 15:05 UTC, CFarcy approved these changes

2023-07-07 15:07 UTC, mabhub requested changes

2023-07-07 15:07 UTC, mabhub commented on src/modules/RA/DataLayer/components/tabs/StyleTab/Style/CategorizeValue.js
> +
```suggestion
```

2023-07-07 15:07 UTC, mabhub commented on src/modules/RA/DataLayer/components/tabs/StyleTab/Style/WizardIcon.js
> +import IconStyleField from './IconStyleField';
Regroup component imports ;)

2023-07-11 07:51 UTC, mabhub approved these changes

2023-07-11 07:52 UTC, CFarcy approved these changes

2023-07-11 07:53 UTC, merged